import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const source=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
function sandbox(fn){const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pstack-test-'));try{fs.cpSync(source,tmp,{recursive:true,filter:p=>!['.git','dist','candidate-dist','.candidate'].includes(path.basename(p))});fn(tmp);}finally{fs.rmSync(tmp,{recursive:true,force:true});}}
function run(root,cmd,env={}){return spawnSync(process.execPath,[path.join(root,'scripts/pstack.mjs'),cmd],{encoding:'utf8',env:{...process.env,...env}});}
function hash(root){const h=crypto.createHash('sha256');function walk(p){for(const n of fs.readdirSync(p).sort()){const f=path.join(p,n);if(fs.statSync(f).isDirectory())walk(f);else{h.update(path.relative(root,f));h.update(fs.readFileSync(f));}}}walk(root);return h.digest('hex');}
test('repeatable build and full coverage',()=>sandbox(r=>{let x=run(r,'build');assert.equal(x.status,0,x.stderr);const h=hash(path.join(r,'candidate-dist'));x=run(r,'build');assert.equal(x.status,0,x.stderr);assert.equal(hash(path.join(r,'candidate-dist')),h);assert.equal(fs.readdirSync(path.join(r,'candidate-dist/skills')).length,fs.readdirSync(path.join(r,'upstream/pstack/skills')).length+1);}));
test('unreviewed upstream cannot replace built output',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const h=hash(path.join(r,'candidate-dist'));fs.appendFileSync(path.join(r,'upstream/pstack/README.md'),'\nchanged');assert.notEqual(run(r,'build').status,0);assert.equal(hash(path.join(r,'candidate-dist')),h);}));
test('matching lock alone does not approve a new snapshot',()=>sandbox(r=>{fs.appendFileSync(path.join(r,'upstream/pstack/README.md'),'\nchanged');const lock=JSON.parse(fs.readFileSync(path.join(r,'upstream.lock.json')));lock.treeSha256=run(r,'digest').stdout.trim();fs.writeFileSync(path.join(r,'upstream.lock.json'),JSON.stringify(lock));const x=run(r,'build');assert.notEqual(x.status,0);assert.match(x.stderr,/not been reviewed/);}));
test('failed reference validation preserves output',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const h=hash(path.join(r,'candidate-dist'));fs.appendFileSync(path.join(r,'codex/runtime.md'),'\n[missing](missing.md)');assert.notEqual(run(r,'build').status,0);assert.equal(hash(path.join(r,'candidate-dist')),h);}));
test('global install is idempotent and links resolve',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const dest=path.join(r,'installed');for(let i=0;i<2;i++){const x=run(r,'install',{PSTACK_SKILLS_DIR:dest});assert.equal(x.status,0,x.stderr);}for(const n of fs.readdirSync(dest))assert.equal(fs.realpathSync(path.join(dest,n)),fs.realpathSync(path.join(r,'dist/skills',n)));}));
test('collision preflight makes no partial installation',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const dest=path.join(r,'installed');fs.mkdirSync(path.join(dest,'why'),{recursive:true});fs.writeFileSync(path.join(dest,'why/keep'),'user');assert.notEqual(run(r,'install',{PSTACK_SKILLS_DIR:dest}).status,0);assert.deepEqual(fs.readdirSync(dest),['why']);assert.equal(fs.readFileSync(path.join(dest,'why/keep'),'utf8'),'user');}));
test('dangling foreign symlink is not treated as an empty slot',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const dest=path.join(r,'installed');fs.mkdirSync(dest);fs.symlinkSync('/does-not-exist-pstack-test',path.join(dest,'why'));assert.notEqual(run(r,'install',{PSTACK_SKILLS_DIR:dest}).status,0);assert.deepEqual(fs.readdirSync(dest),['why']);}));

test('building an update does not change installed output',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);assert.equal(run(r,'install',{PSTACK_SKILLS_DIR:path.join(r,'installed')}).status,0);const h=hash(path.join(r,'dist'));fs.appendFileSync(path.join(r,'codex/runtime.md'),'\nAdditional reviewed guidance.');assert.equal(run(r,'build').status,0);assert.equal(hash(path.join(r,'dist')),h);assert.notEqual(hash(path.join(r,'candidate-dist')),h);}));
test('binary resources survive translation byte-for-byte',()=>sandbox(r=>{const b=Buffer.from([0,255,128,137,13,10,0,200]);const p=path.join(r,'upstream/pstack/skills/architect/assets/probe.bin');fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,b);const lock=JSON.parse(fs.readFileSync(path.join(r,'upstream.lock.json')));lock.treeSha256=run(r,'digest').stdout.trim();for(const f of ['upstream.lock.json','codex/reviewed.json'])fs.writeFileSync(path.join(r,f),JSON.stringify(lock));assert.equal(run(r,'build').status,0);assert.deepEqual(fs.readFileSync(path.join(r,'candidate-dist/skills/architect/assets/probe.bin')),b);}));
test('obsolete owned links are reported without deleting user files',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const dest=path.join(r,'installed');assert.equal(run(r,'install',{PSTACK_SKILLS_DIR:dest}).status,0);fs.symlinkSync(path.join(fs.realpathSync(r),'dist/skills/removed-skill'),path.join(dest,'removed-skill'));const x=run(r,'install',{PSTACK_SKILLS_DIR:dest});assert.equal(x.status,0);assert.match(x.stderr,/Obsolete owned skill link/);assert.ok(fs.lstatSync(path.join(dest,'removed-skill')).isSymbolicLink());}));

test('bundled executable helper runs after packaging',()=>sandbox(r=>{assert.equal(run(r,'build').status,0);const helper=path.join(r,'candidate-dist/skills/show-me-your-work/scripts/log.sh');assert.ok(fs.statSync(helper).mode & 0o111);const log=path.join(r,'decisions.tsv');const x=spawnSync(helper,[log,'test','decision','reason','evidence','passed'],{encoding:'utf8'});assert.equal(x.status,0,x.stderr);assert.match(fs.readFileSync(log,'utf8'),/decision/);}));
